### ISSUE TITLE
Problem with spotcast

### ISSUE THREAD

**Issue by Ramon-Balaguer** [ludeeus/action-ha-config-check#2]
I try to check HA config, but i have this error:
![image](https://user-images.githubusercontent.com/11381646/83854147-93dbdc00-a716-11ea-9ee6-394ee8725308.png)

**Comment by ludeeus** [comment]
Added missing libs here, <https://github.com/ludeeus/action-ha-config-check/commit/b2049e0d7f4aaa9808ca37ff621d0112ad49a79b> try again with @master untill the next release.

**Comment by SteveEdson** [comment]
`zlib` is also required as it is breaking my config check for the following integrations:

```
Failed config
  General Errors: 
    - Platform error device_tracker.bluetooth_tracker - Requirements for bluetooth_tracker not found: ['pybluez==0.22'].
    - Component error: owntracks - Requirements for owntracks not found: ['PyNaCl==1.3.0'].
    - Platform error image_processing.doods - Requirements for doods not found: ['pillow==7.1.2'].
    - Component error: mobile_app - Requirements for mobile_app not found: ['PyNaCl==1.3.0'].
```
